config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'

  resources :options

  resources :imagequestions

  resources :categories

   root 'welcome#index'

  match ':controller/:action/:id/:imagequestion_id', via: [:get]
end

app/models/category.rb
class Category < ActiveRecord::Base
end

app/models/imagequestion.rb
class Imagequestion < ActiveRecord::Base
  belongs_to :category

# Algorith that returns next image
  def self.next category, imagequestion_id
  	return self.where(category: category.id).find(imagequestion_id.intval+1)
  end
end

app/models/option.rb
class Option < ActiveRecord::Base
  belongs_to :imagequestion
end

app/controllers/GameController.rb
class GameController < ApplicationController
  

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:name, :logo)
    end
end

app/controllers/imagequestions_controller.rb
class ImagequestionsController < ApplicationController
  before_action :set_imagequestion, only: [:show, :edit, :update, :destroy]

  # GET /imagequestions
  # GET /imagequestions.json
  def index
    @imagequestions = Imagequestion.all
  end

  # GET /imagequestions/1
  # GET /imagequestions/1.json
  def show
  end

  # GET /imagequestions/new
  def new
    @imagequestion = Imagequestion.new
  end

  # GET /imagequestions/1/edit
  def edit
  end

  # POST /imagequestions
  # POST /imagequestions.json
  def create
    @imagequestion = Imagequestion.new(imagequestion_params)

    respond_to do |format|
      if @imagequestion.save
        format.html { redirect_to @imagequestion, notice: 'Imagequestion was successfully created.' }
        format.json { render :show, status: :created, location: @imagequestion }
      else
        format.html { render :new }
        format.json { render json: @imagequestion.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /imagequestions/1
  # PATCH/PUT /imagequestions/1.json
  def update
    respond_to do |format|
      if @imagequestion.update(imagequestion_params)
        format.html { redirect_to @imagequestion, notice: 'Imagequestion was successfully updated.' }
        format.json { render :show, status: :ok, location: @imagequestion }
      else
        format.html { render :edit }
        format.json { render json: @imagequestion.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /imagequestions/1
  # DELETE /imagequestions/1.json
  def destroy
    @imagequestion.destroy
    respond_to do |format|
      format.html { redirect_to imagequestions_url, notice: 'Imagequestion was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_imagequestion
      @imagequestion = Imagequestion.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def imagequestion_params
      params.require(:imagequestion).permit(:file_name, :hint, :category_id)
    end
end

app/controllers/options_controller.rb
class OptionsController < ApplicationController
  before_action :set_option, only: [:show, :edit, :update, :destroy]

  # GET /options
  # GET /options.json
  def index
    @options = Option.all
  end

  # GET /options/1
  # GET /options/1.json
  def show
  end

  # GET /options/new
  def new
    @option = Option.new
  end

  # GET /options/1/edit
  def edit
  end

  # POST /options
  # POST /options.json
  def create
    @option = Option.new(option_params)

    respond_to do |format|
      if @option.save
        format.html { redirect_to @option, notice: 'Option was successfully created.' }
        format.json { render :show, status: :created, location: @option }
      else
        format.html { render :new }
        format.json { render json: @option.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /options/1
  # PATCH/PUT /options/1.json
  def update
    respond_to do |format|
      if @option.update(option_params)
        format.html { redirect_to @option, notice: 'Option was successfully updated.' }
        format.json { render :show, status: :ok, location: @option }
      else
        format.html { render :edit }
        format.json { render json: @option.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /options/1
  # DELETE /options/1.json
  def destroy
    @option.destroy
    respond_to do |format|
      format.html { redirect_to options_url, notice: 'Option was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_option
      @option = Option.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def option_params
      params.require(:option).permit(:option_label, :option_result, :imagequestion_id)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  before_action :set_category, :set_image, :set_options, only: [:play]
  before_action :set_all_categs, only:[:index]
  
  def index
  end

  def play
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find params[:id]
    end

    def set_image
      @imagequestion = Imagequestion.next(@category, params[:imagequestion_id])
    end

    def set_options
      @options = Option.where imagequestion: @imagequestion.id if @imagequestion  
    end

    def set_all_categs
  		@categories = Category.all
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/imagequestions_helper.rb
module ImagequestionsHelper
end

app/helpers/options_helper.rb
module OptionsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/categories/_form.html.erb
<%= form_for(@category) do |f| %>
  <% if @category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% @category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :logo %><br>
    <%= f.text_field :logo %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing category</h1>

<%= render 'form' %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<h1>Listing categories</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Logo</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td><%= category.name %></td>
        <td><%= category.logo %></td>
        <td><%= link_to 'Show', category %></td>
        <td><%= link_to 'Edit', edit_category_path(category) %></td>
        <td><%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Category', new_category_path %>

app/views/categories/new.html.erb
<h1>New category</h1>

<%= render 'form' %>

<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @category.name %>
</p>

<p>
  <strong>Logo:</strong>
  <%= @category.logo %>
</p>

<%= link_to 'Edit', edit_category_path(@category) %> |
<%= link_to 'Back', categories_path %>

app/views/imagequestions/_form.html.erb
<%= form_for(@imagequestion) do |f| %>
  <% if @imagequestion.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@imagequestion.errors.count, "error") %> prohibited this imagequestion from being saved:</h2>

      <ul>
      <% @imagequestion.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :file_name %><br>
    <%= f.text_field :file_name %>
  </div>
  <div class="field">
    <%= f.label :hint %><br>
    <%= f.text_field :hint %>
  </div>
  <div class="field">
    <%= f.label :category_id %><br>
    <%= f.text_field :category_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/imagequestions/edit.html.erb
<h1>Editing imagequestion</h1>

<%= render 'form' %>

<%= link_to 'Show', @imagequestion %> |
<%= link_to 'Back', imagequestions_path %>

app/views/imagequestions/index.html.erb
<h1>Listing imagequestions</h1>

<table>
  <thead>
    <tr>
      <th>File name</th>
      <th>Text description</th>
      <th>Category</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @imagequestions.each do |imagequestion| %>
      <tr>
        <td><%= imagequestion.file_name %></td>
        <td><%= imagequestion.hint %></td>
        <td><%= imagequestion.category %></td>
        <td><%= link_to 'Show', imagequestion %></td>
        <td><%= link_to 'Edit', edit_imagequestion_path(imagequestion) %></td>
        <td><%= link_to 'Destroy', imagequestion, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Imagequestion', new_imagequestion_path %>

app/views/imagequestions/new.html.erb
<h1>New imagequestion</h1>

<%= render 'form' %>

<%= link_to 'Back', imagequestions_path %>

app/views/imagequestions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>File name:</strong>
  <%= @imagequestion.file_name %>
</p>

<p>
  <strong>Text description:</strong>
  <%= @imagequestion.hint %>
</p>

<p>
  <strong>Category:</strong>
  <%= @imagequestion.category %>
</p>

<%= link_to 'Edit', edit_imagequestion_path(@imagequestion) %> |
<%= link_to 'Back', imagequestions_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Popularity</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/options/_form.html.erb
<%= form_for(@option) do |f| %>
  <% if @option.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@option.errors.count, "error") %> prohibited this option from being saved:</h2>

      <ul>
      <% @option.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :option_label %><br>
    <%= f.text_field :option_label %>
  </div>
  <div class="field">
    <%= f.label :option_result %><br>
    <%= f.check_box :option_result %>
  </div>
  <div class="field">
    <%= f.label :imagequestion_id %><br>
    <%= f.text_field :imagequestion_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/options/edit.html.erb
<h1>Editing option</h1>

<%= render 'form' %>

<%= link_to 'Show', @option %> |
<%= link_to 'Back', options_path %>

app/views/options/index.html.erb
<h1>Listing options</h1>

<table>
  <thead>
    <tr>
      <th>Option label</th>
      <th>Option result</th>
      <th>Imagequestion</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @options.each do |option| %>
      <tr>
        <td><%= option.option_label %></td>
        <td><%= option.option_result %></td>
        <td><%= option.imagequestion %></td>
        <td><%= link_to 'Show', option %></td>
        <td><%= link_to 'Edit', edit_option_path(option) %></td>
        <td><%= link_to 'Destroy', option, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Option', new_option_path %>

app/views/options/new.html.erb
<h1>New option</h1>

<%= render 'form' %>

<%= link_to 'Back', options_path %>

app/views/options/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Option label:</strong>
  <%= @option.option_label %>
</p>

<p>
  <strong>Option result:</strong>
  <%= @option.option_result %>
</p>

<p>
  <strong>Imagequestion:</strong>
  <%= @option.imagequestion %>
</p>

<%= link_to 'Edit', edit_option_path(@option) %> |
<%= link_to 'Back', options_path %>

app/views/welcome/end.html.erb
<h1 class="result">
	<div class="<%=@result%>">
		<%=@result%>
	</div>
	<div>
		<%= link_to 'Play again!', '/start/?category%5Bid%5D%3D'+1.to_s %>

		<%= link_to 'Try another category!', root_path %>
	</div>
</h1>

app/views/welcome/index.html.erb
<h1>Popularity v 0.0.1</h1>
<p>
<% @categories.each do |c| %>
      <ul>
        <li><%= link_to "Play #{c.name} ", play_welcome_path(c) %></li>
      </ul>
    <% end %>
</p>

app/views/welcome/play.html.erb
<h1><%=@imagequestion.hint%></h1>
<%= image_tag("/images/#{@imagequestion.category.id}/#{@imagequestion.file_name}", 
	width: "256")
%>  
<%= form_tag("", method: "get") do %>
<p>
<%=	collection_radio_buttons(:option, :id, @options, :id, :option_label, {}, {}) %>
</p>

<%= submit_tag("Test!") %>

<% end %>
</p>

app/views/welcome/start.html.erb
<h1><%=@imagequestion.hint%></h1>
<%= image_tag("/images/#{@imagequestion.category.id}/#{@imagequestion.file_name}", 
	width: "256")
%>  
<%= form_tag("/end", method: "get") do %>
<p>
<%=	collection_radio_buttons(:option, :id, @options, :id, :option_label, {}, {}) %>
</p>

<%= submit_tag("Test!") %>

<% end %>
</p>